### ISSUE TITLE
New components

### ISSUE THREAD

**Issue by mabitbol** [simonsobs/fgspectra#25]
What new components do we need? 
Current SEDs:
Power law, MBB, free-free, constant
Current power spectrum models:
Power law, arb template file (existing templates: tSZ_150_bat template, kSZ_bat, tSZxCIB)

Spinning dust SED? Power spectrum shape? 
Add requests here

**Comment by dpole** [comment]
About this, I've a pending action on #21

**Comment by jcolinhill** [comment]
perhaps worth asking Giuseppe about CO?

**Comment by msyriac** [comment]
@giuspugl ^ noticed you were pinged here.

**Comment by giuspugl** [comment]
Hello guys, 
power spectra from CO are difficult cause we don't have much measurements at high galactic latitudes. Planck MILCA CO maps were  totally noise dominated ([check this plot from my paper ](https://academic.oup.com/view-large/figure/87787116/stx1029fig7.jpg) ,  the way we  forecast emission from CO at high Gal. latitudes  is described in [Puglisi et al.](https://academic.oup.com/mnras/article/469/3/2982/3786425) , we fit for E and B spectra  a decreasing power law in D_ell  with alpha_CO = -1.78 and amplitude A~ 1e-4 uK^2 ( assuming 1 % fract. polarization which is fairly conservative) . Is this something you need?

**Comment by dpole** [comment]
I think that CO spectrum depends quite a bit on galactic mask you choose -- as any galactic emission. I think we should decide on a mask first, so that we have all the components coherent between each other. Once we have it, we should probably just take the Planck CO map, mask it and measure the spectrum. About polarization, we should probably let the user define the polarization fraction. What do you think?
