### ISSUE TITLE
License

### ISSUE THREAD

**Issue by damonge** [simonsobs/fgspectra#37]
Add a license!

**Comment by dpole** [comment]
Good point. It seems to me that we don't have limitations. GNUv3 could be a natural choice, but we may even decide for a more permissive one (or less permissive, if someone prefers). What do people think? @xzackli @mabitbol

**Comment by damonge** [comment]
I use [BSD](https://github.com/LSSTDESC/NaMaster/blob/master/LICENSE) because GPLv3 self-replicates like a virus: all codes based on your code need to be released under GPLv3, whereas that's not the case for BSD. It's more permissive in that sense, with the downside that people can use your code to make non-open code.

**Comment by mabitbol** [comment]
I am not very familiar with the difference licenses. In general I am happy for anyone to use it with a reference to our github.

On Nov 11, 2020, at 3:37 AM, David Alonso <notifications@github.com<mailto:notifications@github.com>> wrote:



I use BSD<https://github.com/LSSTDESC/NaMaster/blob/master/LICENSE> because GPLv3 self-replicates like a virus: all codes based on your code need to be released under GPLv3, whereas that's not the case for BSD. It's more permissive in that sense, with the downside that people can use your code to make non-open code.

**Comment by dpole** [comment]
Sure, to my memory BSD does have an attribution clause. MIT is also a possibility and is very similar (almost interchangeable) with some of the BSD flavors.

**Comment by xzackli** [comment]
Happy with BSD, looks like that's typical for SO software.
