### ISSUE TITLE
Linear combination of templates?

### ISSUE THREAD

**Issue by damonge** [simonsobs/fgspectra#8]
I thought it might be useful to support a power spectrum class corresponding to an arbitrary linear combination of input templates with free coefficients.

Not necessarily super urgent.

**Comment by dpole** [comment]
We have added a [class](https://github.com/simonsobs/fgspectra/blob/06918d56f81429da5b6a053bc51a3ace25d8691c/fgspectra/cross.py#L14)
to sum uncorrelated components (currently on a development branch #20)

Please also have a look at the last three cells of [this notebook](https://github.com/simonsobs/fgspectra/blob/06918d56f81429da5b6a053bc51a3ace25d8691c/notebooks/correlated_dust_sync.ipynb)

It just takes the sum and not a linear combination because in the current logic (not in place at that time) the normalization should be controlled using the arguments of the cross spectra that you are summing.
