### ISSUE TITLE
CorrelatedFactorizedCrossSpectrum

### ISSUE THREAD

**Issue by mabitbol** [simonsobs/fgspectra#9]
I think this should take two frequency functions and two power spectrum functions?
Currently it takes callables with shape (comp, ... freqs) and (...,comp,comp,ell) but we dont have anything to generate those.

**Comment by dpole** [comment]
About the frequency functions, I was wondering the same thing. For the power spectrum, I think we need a single function because of the correlated term.
Currently we have two ways of creating the latter:
* from file: passing a nested list of files
* using PowerLaw and passing an alpha with shape (2,2)

**Comment by dpole** [comment]
I think this is addressed in #19, relevant info is also discussed in #15
